version: "3.9"
services:
    sdk:
        profiles:
            - testing
        build: .
        ports:
            - 8080:8080
        depends_on:
            - redis
            - kafka
        environment: 
            - TOKEN_SALT=secret
            - REDIS_URL=redis
            - KAFKA_URL=kafka:9092
    redis:
        image: redis
        hostname: redis
        container_name: redis
        ports:
            - 6379:6379
    zookeeper:
        image: wurstmeister/zookeeper
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.0.188
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181