name: Prepare release with a Pull request
on: 
  workflow_dispatch:
    inputs:
      release-version:
        description: "release version"
        required: true

jobs:
  prepare-release:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
    
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: bump package version
        run: npm version --allow-same-version --no-git-tag-version ${{ github.event.inputs.release-version }} 
       
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: release/${{ github.event.inputs.release-version }}
          title: '[Release] welcome ${{ github.event.inputs.release-version  }}'
          commit-message: "welcome ${{ github.event.inputs.release-version  }} :bookmark:"
          delete-branch: false
          labels: release
          body: "Don't forget to check the changelog :rocket:"
          token: ${{ secrets.GITHUB_TOKEN }}
